# Railway Configuration for CarbonTwin Backend

[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PYTHONPATH = "/app"
PORT = "5000"
FLASK_ENV = "production"
FLASK_DEBUG = "False"

# Database
DATABASE_URL = "${{ DATABASE_URL }}"

# Authentication 
CLERK_SECRET_KEY = "${{ CLERK_SECRET_KEY }}"

# API Keys
CHATGPT5_API_KEY = "${{ CHATGPT5_API_KEY }}"

# Security
SECRET_KEY = "${{ SECRET_KEY }}"
JWT_SECRET = "${{ JWT_SECRET }}"

# Blockchain
ETHEREUM_RPC_URL = "${{ ETHEREUM_RPC_URL }}"
PRIVATE_KEY = "${{ PRIVATE_KEY }}"
CONTRACT_ADDRESS = "${{ CONTRACT_ADDRESS }}"

# External APIs
WEATHER_API_KEY = "${{ WEATHER_API_KEY }}"
CARBON_TRACKER_API_KEY = "${{ CARBON_TRACKER_API_KEY }}"

# Logging
LOG_LEVEL = "INFO"
LOG_FILE = "carbontwin.log"

# Real-time Features
SOCKETIO_ASYNC_MODE = "threading"
SOCKETIO_CORS_ALLOWED_ORIGINS = "*"

# AI Configuration
AI_MODEL_VERSION = "gpt-4"
AI_TEMPERATURE = "0.3"
AI_MAX_TOKENS = "1000"
